cards = {
"1 Sol Ring",
"14 Swamp",
"11 Mountain",
"1 Ancient Craving",
"1 Vampiric Dragon",
"1 Shadowblood Ridge",
"1 Tainted Peak",
"1 Temple of the False God",
"1 Night\u0027s Whisper",
"1 Fire Diamond",
"1 Charcoal Diamond",
"1 Rakdos Carnarium",
"1 Rakdos Signet",
"1 Exotic Orchard",
"1 Malakir Bloodwitch",
"1 Vampire Nighthawk",
"1 Anowon, the Ruin Sage",
"1 Butcher of Malakir",
"1 Urge to Feed",
"1 Nirkana Revenant",
"1 Bloodlord of Vaasgoth",
"1 Command Tower",
"1 Swiftfoot Boots",
"1 Blasphemous Act",
"1 Rakish Heir",
"1 Falkenrath Noble",
"1 Stromkirk Captain",
"1 Blood Artist",
"1 Dark Impostor",
"1 Underworld Connections",
"1 Necropolis Regent",
"1 Rakdos Charm",
"1 Vandalblast",
"1 Temple of Malice",
"1 Myriad Landscape",
"1 Unstable Obelisk",
"1 Commander's Sphere",
"1 Mob Rule",
"1 Damnable Pact",
"1 Smoldering Marsh",
"1 Falkenrath Gorger",
"1 Indulgent Aristocrat",
"1 Foreboding Ruins",
"1 Avacyn's Judgment",
"1 Stensia Masquerade",
"1 Stromkirk Condemned",
"1 Stromkirk Occultist",
"1 Bloodline Necromancer",
"1 Bloodsworn Steward",
"1 Crimson Honor Guard",
"1 Patron of the Vein",
"1 Path of Ancestry",
"1 Unclaimed Territory",
"1 Sanctum Seeker",
"1 Champion of Dusk",
"1 Bloodtracker",
"1 Cordial Vampire",
"1 Arcane Signet",
"1 Anje's Ravager",
"1 Molten Echoes",
"1 Feed the Swarm",
"1 Strefan, Maurer Progenitor",
"1 Bloodtithe Harvester",
"1 Timothar, Baron of Bats",
"1 Crossway Troublemakers",
"1 Sinister Waltz",
"1 Scion of Opulence",
"1 Glass-Cast Heart",
"1 Kamber, the Plunderer",
"1 Midnight Arsonist",
"1 Olivia's Wrath",
"1 Predators' Hour",
"1 Markov Enforcer",
"1 Shadowgrange Archfiend",
"1 Arterial Alchemy",
"1 Laurine, the Diversion",
"1 Imposing Grandeur"
}
    
for card in cards:
    card = card.lower().replace(' ', '_').replace('\'', '_').replace(',', '_')[2:]
    url = 'https://static.starcitygames.com/sales/cardscans/POPUPS/' + card + '.jpg';
    print(url)